### ISSUE TITLE
DaggerAppComponent error when build project

### ISSUE THREAD

**Issue by mustafakibar** [spookyUnknownUser/PremiereDowngrader#2]
I was clone this project then I'm build it and getting this error:

`Error:(21, 38) Kotlin: Unresolved reference: DaggerAppComponent`

> IntelliJ IDEA 2017.3.2
> Build #IU-173.4127.17, built on December 19, 2017
> JRE: 1.8.0_152-release-1024-b8 amd64
> JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
> Windows 10 10.0

**Comment by spookyuser** [comment]
Hey, thanks for the bug report! 

I just tried a fresh clone and build now and it seemed to work for me. 
Could you try and do a fresh clone then post the output of `gradlew jar`,  from the command 

Might give a more specific error.
